name: Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    publish:
        name: Build and Publish
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Build
              run: |
                  npm ci
                  npm run build
            - name: Upload & release
              uses: mnao305/chrome-extension-upload@2.2.0
              with:
                  file-path: dist/chrome/chrome.zip
                  extension-id: hogefuga(extension id)
                  client-id: ${{ secrets.CLIENT_ID }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
