name: Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
        name: Publish webextension
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Build
              run: |
                  npm ci
                  npm run build
            - name: Upload & release
              uses: mnao305/chrome-extension-upload@2.2.0
              with:
                  file-path: dist/chrome/file.zip
                  extension-id: hogefuga(extension id)
                  client-id: ${{ secrets.CLIENT_ID }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}

    upload:
        needs: [build]
        name: Upload files on Artifact
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/upload-artifact@v3
              with:
                  name: railflow-artifact
                  path: dist
