name: Upload Built files

on:
    push:
        branches:
            - main

jobs:
    upload:
        name: Build and Upload files on Artifact
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Build
              run: |
                  npm ci
                  npm run build
            - name: Uploading Files on Artifact
            - uses: actions/upload-artifact@v3
              with:
                  name: railflow-artifact
                  path: dist
